### ISSUE TITLE
급식 FlatList

### ISSUE THREAD

**Issue by olsi10** [2023-mirimi/mirimi-client#12]
일(date) 기반으로 요일(day)가져오기
요일 배열을 만들고 getDate 사용해보기

**Comment by hyennin** [comment]
내가 햇어

**Comment by hyennin** [comment]
미앙 614 이렇게 뜨는게 왕킹받아서 그만.. 할 일을 뺏어버렷군

**Comment by olsi10** [comment]
뭐!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
진짜고맙지!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
바코드 내가 뺏어주마.
