### ISSUE TITLE
공모전별 TabView를 만들어야 하는데

### ISSUE THREAD

**Issue by olsi10** [2023-mirimi/mirimi-client#7]
코드를 재사용할 방법이 있을지...
DATA 배열에 있는 거의 내용을 바꿔서 컴포넌트 재사용하고 싶은데
DATA 배열 꺼내기 -> Item 컴포넌트에 넣음 -> Competition에서 FlatList로 뿌려줌

**Comment by hyennin** [comment]
TabView안에 들어갈 내용을 컴포넌트로 하고 DATA 배열을 따로 파일로 빼서 쓰면은.. 되지 않을까?

**Comment by olsi10** [comment]
굿 아이디어!
![image](https://github.com/2023-mirimi/mirimi-client/assets/87300199/05c87f7d-8f74-4daa-aba8-fb12b28eef9d)
